// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include <CANTalon.h>
#include <LiveWindow/LiveWindow.h>
#include <RobotDrive.h>
#include <RobotMap.h>


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveTrainFrontRight;
std::shared_ptr<SpeedController> RobotMap::driveTrainFrontLeft;
std::shared_ptr<SpeedController> RobotMap::driveTrainBackRight;
std::shared_ptr<SpeedController> RobotMap::driveTrainBackLeft;
std::shared_ptr<RobotDrive> RobotMap::driveTrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainFrontRight.reset(new Talon(2));
    lw->AddActuator("DriveTrain", "FrontRight", (Talon&) driveTrainFrontRight);
    
    driveTrainFrontLeft.reset(new Talon(3));
    lw->AddActuator("DriveTrain", "FrontLeft", (Talon&) driveTrainFrontLeft);
    
    driveTrainBackRight.reset(new Talon(0));
    lw->AddActuator("DriveTrain", "BackRight", (Talon&) driveTrainBackRight);
    
    driveTrainBackLeft.reset(new Talon(1));
    lw->AddActuator("DriveTrain", "BackLeft", (Talon&) driveTrainBackLeft);
    
    driveTrainRobotDrive41.reset(new RobotDrive(driveTrainFrontLeft, driveTrainBackLeft,
              driveTrainFrontRight, driveTrainBackRight));
    
    driveTrainRobotDrive41->SetSafetyEnabled(true);
        driveTrainRobotDrive41->SetExpiration(0.1);
        driveTrainRobotDrive41->SetSensitivity(0.5);
        driveTrainRobotDrive41->SetMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
