// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveTrainfrontLeft;
std::shared_ptr<SpeedController> RobotMap::driveTrainfrontRight;
std::shared_ptr<SpeedController> RobotMap::driveTrainbackLeft;
std::shared_ptr<SpeedController> RobotMap::driveTrainbackRight;
std::shared_ptr<RobotDrive> RobotMap::driveTrainTankDriveTrain;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainfrontLeft.reset(new Talon(3));
    lw->AddActuator("DriveTrain", "frontLeft", (Talon&) driveTrainfrontLeft);
    
    driveTrainfrontRight.reset(new Talon(2));
    lw->AddActuator("DriveTrain", "frontRight", (Talon&) driveTrainfrontRight);
    
    driveTrainbackLeft.reset(new Talon(1));
    lw->AddActuator("DriveTrain", "backLeft", (Talon&) driveTrainbackLeft);
    
    driveTrainbackRight.reset(new Talon(0));
    lw->AddActuator("DriveTrain", "backRight", (Talon&) driveTrainbackRight);
    
    driveTrainTankDriveTrain.reset(new RobotDrive(driveTrainfrontLeft, driveTrainbackLeft,
              driveTrainfrontRight, driveTrainbackRight));
    
    driveTrainTankDriveTrain->SetSafetyEnabled(true);
        driveTrainTankDriveTrain->SetExpiration(0.1);
        driveTrainTankDriveTrain->SetSensitivity(0.5);
        driveTrainTankDriveTrain->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
